---
name: codespell

on:
  pull_request:
  push:

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - name: mycms-checkout
        uses: actions/checkout@v4
      - uses: codespell-project/actions-codespell@master
        with:
          ignore_words_file: ./.codespell-ignore-words
